# Test suite to check long-lived artis dictionary files 
# 
# Tests against suggested values from this unofficial piece of documentation. Not a lot of detail 
# contained within official documentation for the EMLassemblyline. This was generated by Claude Sonnet 4.6
# given the unofficial documentation contents linked below and the run_EMLassemblyline_for_artis_dictionaries.R
# script. Run this after changing or adding values to long-lived dictionaries before running through
# EMLassemblyline (EAL) workflow, and/or after running through the EAL workflow to check that things are 
# working as expected. The EAL function make_eml() has a lot of embedded validation, this script is intended 
# to supplement that validation based on my first use of this EAL workflow. 

# Based on documentation: https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=197025

## artis dictionaries:
# artis_dictionary_tbl_attributes.txt
# artis_dictionary_tbl_attributes_catvars.txt
# artis_dictionary_tbl.txt
# artis_dictionary_hs_version.txt
# personnel.txt

{
  library(testthat)
  library(readr)
  library(dplyr)
  library(purrr)
  library(glue)
  library(here)
}

# ---- Helper paths -----------------------------------------------------------

{
path_metadata_dir <- here::here("artis_metadata_files")
path_templates    <- here::here("artis_metadata_files", "metadata_templates")
path_dict_attr    <- here::here("artis_dictionaries", "artis_dictionary_tbl_attributes.txt")
path_dict_catvars <- here::here("artis_dictionaries", "artis_dictionary_tbl_attributes_catvars.txt")
path_dict_tbl     <- here::here("artis_dictionaries", "artis_dictionary_tbl.txt")
path_dict_hs      <- here::here("artis_dictionaries", "artis_dictionary_hs_version.txt")
}

# ---- Load dictionaries ------------------------------------------------------

# read with method that excludes excel's crazy and sneaky character additions

artis_defs_attr <- readr::read_tsv(path_dict_attr, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

artis_defs_catvars <- readr::read_tsv(path_dict_catvars, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

artis_dict_tbl <- readr::read_tsv(path_dict_tbl, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

artis_dict_hs <- readr::read_tsv(path_dict_hs, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

personnel <- readr::read_tsv(
  file.path(path_templates, "personnel.txt"),
  show_col_types = FALSE
)

# ---- Helper: UTF-8 encoding checker -----------------------------------------

check_utf8 <- function(tbl) {
  char_cols <- tbl |> dplyr::select(where(is.character))
  purrr::map(names(char_cols), \(col) {
    vals <- char_cols[[col]]
    bad  <- which(!is.na(vals) & !validUTF8(vals))
    if (length(bad) > 0) glue::glue("{col} rows {paste(bad, collapse = ', ')}")
  }) |> purrr::discard(is.null)
}

# ---- Fixed reference values -------------------------------------------------

valid_classes      <- c("numeric", "categorical", "character", "Date")

# The 8 canonical ARTIS output / reference tables.
# Update this list when a new table is added to the ARTIS data release.
valid_tbl_names <- c(
  "consumption",
  "reference_countries",
  "reference_hs6_taxa_resolution",
  "reference_hs6",
  "reference_production",
  "reference_sciname",
  "reference_trade_baci",
  "trade"
)

# ---- artis_dictionary_tbl_attributes.txt tests ------------------------------

test_that("artis_defs_attr has no invalid class values", {
  bad <- artis_defs_attr |>
    dplyr::filter(!class %in% valid_classes)
  expect_equal(
    nrow(bad), 0,
    label = paste("Invalid class values:", paste(unique(bad$class), collapse = ", "))
  )
})

test_that("artis_defs_attr: numeric attributes have units", {
  bad <- artis_defs_attr |>
    dplyr::filter(class == "numeric", is.na(unit) | unit == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Numeric attributes missing units:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: non-numeric attributes have blank units", {
  bad <- artis_defs_attr |>
    dplyr::filter(class != "numeric", !is.na(unit) & unit != "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Non-numeric attributes with units:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: Date attributes have dateTimeFormatString", {
  bad <- artis_defs_attr |>
    dplyr::filter(class == "Date", is.na(dateTimeFormatString) | dateTimeFormatString == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Date attributes missing format string:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: non-Date attributes have blank dateTimeFormatString", {
  bad <- artis_defs_attr |>
    dplyr::filter(class != "Date", !is.na(dateTimeFormatString) & dateTimeFormatString != "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Non-Date attributes with format string:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: all attributeDefinitions are non-empty", {
  bad <- artis_defs_attr |>
    dplyr::filter(is.na(attributeDefinition) | attributeDefinition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Attributes missing definitions:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: no non-UTF-8 characters in character columns", {
  bad_rows <- check_utf8(artis_defs_attr)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

# ---- artis_dictionary_tbl_attributes_catvars.txt tests ----------------------

test_that("artis_defs_catvars: all definitions are non-empty", {
  bad <- artis_defs_catvars |>
    dplyr::filter(is.na(definition) | definition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste(
      "Catvars missing definitions - table:", paste(bad$datatable_general_name, collapse = ", "),
      "attribute:", paste(bad$attributeName, collapse = ", "),
      "code:", paste(bad$code, collapse = ", ")
    )
  )
})

test_that("artis_defs_catvars: no non-UTF-8 characters in character columns", {
  bad_rows <- check_utf8(artis_defs_catvars)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

test_that("artis_defs_catvars: all datatable_general_name values exist in artis_dictionary_tbl.txt", {
  known_tables <- artis_dict_tbl$datatable_general_name
  bad <- artis_defs_catvars |>
    dplyr::filter(!datatable_general_name %in% known_tables)
  expect_equal(
    nrow(bad), 0,
    label = paste(
      "datatable_general_name values not in artis_dictionary_tbl.txt:",
      paste(unique(bad$datatable_general_name), collapse = ", ")
    )
  )
})

# ---- artis_dictionary_tbl.txt tests -----------------------------------------

test_that("artis_dict_tbl: required columns are present", {
  required_cols <- c("datatable_general_name", "definition")
  missing <- setdiff(required_cols, names(artis_dict_tbl))
  expect_equal(length(missing), 0, label = paste("Missing columns:", paste(missing, collapse = ", ")))
})

test_that("artis_dict_tbl: contains exactly the expected set of table names", {
  actual <- sort(artis_dict_tbl$datatable_general_name)
  expected <- sort(valid_tbl_names)
  expect_equal(actual, expected)
})

test_that("artis_dict_tbl: no duplicate datatable_general_name values", {
  dupes <- artis_dict_tbl |>
    dplyr::count(datatable_general_name) |>
    dplyr::filter(n > 1)
  expect_equal(
    nrow(dupes), 0,
    label = paste("Duplicate table names:", paste(dupes$datatable_general_name, collapse = ", "))
  )
})

test_that("artis_dict_tbl: all definitions are non-empty", {
  bad <- artis_dict_tbl |>
    dplyr::filter(is.na(definition) | definition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Tables missing definitions:", paste(bad$datatable_general_name, collapse = ", "))
  )
})

test_that("artis_dict_tbl: no non-UTF-8 characters in character columns", {
  bad_rows <- check_utf8(artis_dict_tbl)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

# ---- artis_dictionary_hs_version.txt tests ----------------------------------

test_that("artis_dict_hs: required columns are present", {
  required_cols <- c("attributeName", "code", "definition")
  missing <- setdiff(required_cols, names(artis_dict_hs))
  expect_equal(length(missing), 0, label = paste("Missing columns:", paste(missing, collapse = ", ")))
})

test_that("artis_dict_hs: attributeName column contains only 'hs_version'", {
  bad <- artis_dict_hs |>
    dplyr::filter(attributeName != "hs_version")
  expect_equal(
    nrow(bad), 0,
    label = paste("Unexpected attributeName values:", paste(unique(bad$attributeName), collapse = ", "))
  )
})

test_that("artis_dict_hs: code values match expected format 'HS' followed by 2 digits", {
  bad <- artis_dict_hs |>
    dplyr::filter(!grepl("^HS\\d{2}$", code))
  expect_equal(
    nrow(bad), 0,
    label = paste("Malformed HS version codes:", paste(bad$code, collapse = ", "))
  )
})

test_that("artis_dict_hs: no duplicate codes", {
  dupes <- artis_dict_hs |>
    dplyr::count(code) |>
    dplyr::filter(n > 1)
  expect_equal(
    nrow(dupes), 0,
    label = paste("Duplicate HS codes:", paste(dupes$code, collapse = ", "))
  )
})

test_that("artis_dict_hs: all definitions are non-empty", {
  bad <- artis_dict_hs |>
    dplyr::filter(is.na(definition) | definition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("HS codes missing definitions:", paste(bad$code, collapse = ", "))
  )
})

test_that("artis_dict_hs: no non-UTF-8 characters in character columns", {
  bad_rows <- check_utf8(artis_dict_hs)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

# ---- personnel.txt tests ----------------------------------------------------

test_that("personnel: basic roles are present", {
  expect_true("creator" %in% personnel$role, label = "At least one creator required")
  expect_true("contact" %in% personnel$role, label = "At least one contact required")
  expect_true("PI" %in% personnel$role, label = "At least one PI required")
  expect_true("metadataProvider" %in% personnel$role, label = "At least one metadataProvider required")
})

test_that("personnel: userId format is 16-digit ORCID (XXXX-XXXX-XXXX-XXXX)", {
  # Per EAL docs: userId should be just the ORCID number, not full URL
  non_empty_ids <- personnel |>
    dplyr::filter(!is.na(userId) & userId != "")
  bad <- non_empty_ids |>
    dplyr::filter(!grepl("^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$", userId))
  expect_equal(
    nrow(bad), 0,
    label = paste("Invalid userId format:", paste(bad$userId, collapse = ", "))
  )
})

test_that("personnel: required columns are present", {
  required_cols <- c("givenName", "surName", "organizationName", "electronicMailAddress", "userId", "role")
  missing <- setdiff(required_cols, names(personnel))
  expect_equal(length(missing), 0, label = paste("Missing columns:", paste(missing, collapse = ", ")))
})

test_that("personnel: no non-UTF-8 characters in character columns", {
  bad_rows <- check_utf8(personnel)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

