# Test suite to check long-lived artis dictionary files 
# 
# Tests against suggested values from this unofficial piece of documentation. Not a lot of detail 
# contained within offical documentation for the EMLassemblyline. This was generated by Claude Donnet 4.6
# given the unoffical documentation contents linked below and the run_EMLassemblyline_for_metadata-files.R
# script. Can run this after changing or addding values to long-lived dictionaries before running through
# EMLassemblyline (EAL) workflow, and/or after running through the EAL workflow to check that things are 
# working as expected. The EAL function make_eml() has a lot of embedded validation, this script is intended 
# to supplement that validation based on my first use of this EAL workflow. 

# Based on documentation: https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=197025

# artis dictonaries:
# artis_dictionary_tbl_attributes.txt
# artis_dictionary_tbl_attributes_catvars.txt
# personnel.txt


library(testthat)
library(readr)
library(dplyr)

# ---- Helper paths -----------------------------------------------------------

path_templates <- "./metadata-files/metadata_templates"
path_dict_attr <- "artis_dictionary_tbl_attributes.txt"
path_dict_catvars <- "./metadata-files/artis_dictionary_tbl_attributes_catvars.txt"

# ---- Load dictionaries ------------------------------------------------------

artis_defs_attr <- readr::read_tsv(path_dict_attr, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

artis_defs_catvars <- readr::read_tsv(path_dict_catvars, show_col_types = FALSE, na = "NA") |>
  dplyr::mutate(across(where(is.character), \(x) iconv(x, from = "Windows-1252", to = "UTF-8")))

personnel <- readr::read_tsv(
  file.path(path_templates, "personnel.txt"),
  show_col_types = FALSE
)

attr_files <- list.files(path_templates, pattern = "^attributes_.*\\.txt$", full.names = TRUE)
catvars_files <- list.files(path_templates, pattern = "^catvars_.*\\.txt$", full.names = TRUE)

# ---- Tests ------------------------------------------------------------------

test_that("artis_defs_attr has no invalid class values", {
  valid_classes <- c("numeric", "categorical", "character", "Date")
  bad <- artis_defs_attr |>
    filter(!class %in% valid_classes)
  expect_equal(
    nrow(bad), 0,
    label = paste("Invalid class values:", paste(unique(bad$class), collapse = ", "))
  )
})

test_that("artis_defs_attr: numeric attributes have units", {
  bad <- artis_defs_attr |>
    filter(class == "numeric", is.na(unit) | unit == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Numeric attributes missing units:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: non-numeric attributes have blank units", {
  bad <- artis_defs_attr |>
    filter(class != "numeric", !is.na(unit) & unit != "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Non-numeric attributes with units:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: Date attributes have dateTimeFormatString", {
  bad <- artis_defs_attr |>
    filter(class == "Date", is.na(dateTimeFormatString) | dateTimeFormatString == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Date attributes missing format string:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: non-Date attributes have blank dateTimeFormatString", {
  bad <- artis_defs_attr |>
    filter(class != "Date", !is.na(dateTimeFormatString) & dateTimeFormatString != "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Non-Date attributes with format string:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: all attributeDefinitions are non-empty", {
  bad <- artis_defs_attr |>
    filter(is.na(attributeDefinition) | attributeDefinition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste("Attributes missing definitions:", paste(bad$attributeName, collapse = ", "))
  )
})

test_that("artis_defs_attr: no non-UTF-8 characters in character columns", {
  char_cols <- artis_defs_attr |> select(where(is.character))
  bad_rows <- purrr::map(names(char_cols), \(col) {
    vals <- char_cols[[col]]
    bad <- which(!is.na(vals) & !validUTF8(vals))
    if (length(bad) > 0) glue::glue("{col} rows {paste(bad, collapse=', ')}")
  }) |> purrr::discard(is.null)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

test_that("artis_defs_catvars: all definitions are non-empty", {
  bad <- artis_defs_catvars |>
    filter(is.na(definition) | definition == "")
  expect_equal(
    nrow(bad), 0,
    label = paste(
      "Catvars missing definitions - table:", paste(bad$datatable_general_name, collapse = ", "),
      "attribute:", paste(bad$attributeName, collapse = ", "),
      "code:", paste(bad$code, collapse = ", ")
    )
  )
})

test_that("artis_defs_catvars: no non-UTF-8 characters in character columns", {
  char_cols <- artis_defs_catvars |> select(where(is.character))
  bad_rows <- purrr::map(names(char_cols), \(col) {
    vals <- char_cols[[col]]
    bad <- which(!is.na(vals) & !validUTF8(vals))
    if (length(bad) > 0) glue::glue("{col} rows {paste(bad, collapse=', ')}")
  }) |> purrr::discard(is.null)
  expect_equal(length(bad_rows), 0, label = paste("Bad encoding in:", paste(bad_rows, collapse = "; ")))
})

test_that("personnel: basic roles are present", {
  expect_true("creator" %in% personnel$role, label = "At least one creator required")
  expect_true("contact" %in% personnel$role, label = "At least one contact required")
  expect_true("PI" %in% personnel$role, label = "At least one PI required")
  expect_true("metadataProvider" %in% personnel$role, label = "At least one metadataProvider required")
})

test_that("personnel: userId format is 16-digit ORCID (XXXX-XXXX-XXXX-XXXX)", {
  # Per EAL docs: userId should be just the ORCID number, not full URL
  non_empty_ids <- personnel |>
    filter(!is.na(userId) & userId != "")
  bad <- non_empty_ids |>
    filter(!grepl("^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$", userId))
  expect_equal(
    nrow(bad), 0,
    label = paste("Invalid userId format:", paste(bad$userId, collapse = ", "))
  )
})

test_that("EAL attributes templates: class column has only valid values", {
  valid_classes <- c("numeric", "categorical", "character", "Date")
  purrr::walk(attr_files, \(f) {
    tbl <- readr::read_tsv(f, show_col_types = FALSE)
    bad <- tbl |> filter(!class %in% valid_classes)
    expect_equal(
      nrow(bad), 0,
      label = paste0(basename(f), ": invalid class values: ", paste(unique(bad$class), collapse = ", "))
    )
  })
})

test_that("EAL attributes templates: numeric attributes have units, non-numeric do not", {
  purrr::walk(attr_files, \(f) {
    tbl <- readr::read_tsv(f, show_col_types = FALSE)
    missing_units <- tbl |> filter(class == "numeric", is.na(unit) | unit == "")
    extra_units   <- tbl |> filter(class != "numeric", !is.na(unit) & unit != "")
    expect_equal(nrow(missing_units), 0,
      label = paste0(basename(f), ": numeric missing units: ", paste(missing_units$attributeName, collapse = ", ")))
    expect_equal(nrow(extra_units), 0,
      label = paste0(basename(f), ": non-numeric with units: ", paste(extra_units$attributeName, collapse = ", ")))
  })
})

test_that("EAL attributes templates: Date attributes have dateTimeFormatString", {
  purrr::walk(attr_files, \(f) {
    tbl <- readr::read_tsv(f, show_col_types = FALSE)
    bad <- tbl |> filter(class == "Date", is.na(dateTimeFormatString) | dateTimeFormatString == "")
    expect_equal(nrow(bad), 0,
      label = paste0(basename(f), ": Date attributes missing format: ", paste(bad$attributeName, collapse = ", ")))
  })
})

test_that("EAL attributes templates: attributeDefinition is non-empty", {
  purrr::walk(attr_files, \(f) {
    tbl <- readr::read_tsv(f, show_col_types = FALSE)
    bad <- tbl |> filter(is.na(attributeDefinition) | attributeDefinition == "")
    expect_equal(nrow(bad), 0,
      label = paste0(basename(f), ": attributes missing definitions: ", paste(bad$attributeName, collapse = ", ")))
  })
})

test_that("EAL catvars templates: all definitions are non-empty", {
  purrr::walk(catvars_files, \(f) {
    tbl <- readr::read_tsv(f, show_col_types = FALSE)
    bad <- tbl |> filter(is.na(definition) | definition == "")
    expect_equal(nrow(bad), 0,
      label = paste0(basename(f), ": catvars missing definitions - codes: ", paste(bad$code, collapse = ", ")))
  })
})
